# =====================================
# Application
# =====================================
spring.application.name=sb-ecommerce

# =====================================
# H2 Database
# =====================================
#spring.datasource.url=jdbc:h2:mem:ravanan
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.generate-unique-name=false

# =====================================
# H2 Console
# =====================================
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true

# =====================================
# JPA / Hibernate
# =====================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================================
# JWT Configuration
# =====================================
spring.app.jwtSecret=YXRzdG9uZWJlZ2FuZHJld2ZhbW91c3NvbGRpZXJjbGltYmNhc2VtaWNlZmxpZ2h0bG8=
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName=springBootECom

# =====================================
# Project Properties
# =====================================
project.image=images/

# =====================================
# Logging (Enable only while debugging)
# =====================================
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG

spring.ecom.app.jwtCookie=sbecomcookie

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect